var arr = [
  "Hey! I love JavaScript.",
  "Work hard, stay humble.",
  "You can do it!!!",
  "Code. Sleep. Repeat.",
  "Every bug teaches something.",
  "Small steps every day.",
  "Dream big, code bigger.",
  "Practice makes progress.",
  "Never stop learning.",
  "Errors are proof you're trying.",
  "Push yourself beyond limits.",
  "One line of code at a time.",
  "Stay curious, keep building.",
  "Your future self will thank you.",
  "Coding is creating magic.",
  "Keep calm and debug.",
  "Consistency beats motivation.",
  "Today's effort is tomorrow's success.",
  "Think. Code. Improve.",
  "Success starts with one commit.",
  "Build projects, not excuses.",
  "Learn by doing.",
  "Make your dreams executable.",
  "Focus on progress, not perfection.",
  "Believe in your skills.",
  "Great developers never stop learning.",
  "Every expert was once a beginner.",
  "Turn coffee into code",
  "Trust the process.",
  "Your next project could change everything.",
  "Write clean code.",
  "Coding is a superpower.",
  "Keep pushing forward.",
  "One bug closer to success.",
  "Be fearless while learning.",
  "Debug like a detective.",
  "Create. Learn. Repeat.",
  "Your code tells your story.",
  "Stay patient, stay persistent."
];